name: spring-kafka-avro-test-ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: isbang/compose-action@v0.1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - run: ./gradlew test